[phases.setup]
nixPkgs = [
  "php80",
  "php80Packages.composer",
  "php80Extensions.curl",
  "php80Extensions.mbstring",
  "php80Extensions.openssl",
  "php80Extensions.pdo",
  "php80Extensions.pdo_mysql",
  "php80Extensions.tokenizer",
  "php80Extensions.xml",
  "php80Extensions.bcmath",
  "php80Extensions.fileinfo",
  "nginx",
  "nodejs_18",
  "npm-9_x",
  "libmysqlclient"
]